const jwt = require('jsonwebtoken');
const User = require('../models/User');

const protect = async (req, res, next) => {
  try {
    let token;
    
    if (req.headers.authorization && req.headers.authorization.startsWith('Bearer')) {
      token = req.headers.authorization.split(' ')[1];
    }
    
    if (!token) {
      return res.status(401).json({ success: false, message: 'Chưa đăng nhập, vui lòng đăng nhập để truy cập' });
    }
    
    // Decode "fake" token generated by frontend: btoa(id:role:expiry).random
    const base64Part = token.split('.')[0];
    const decodedStr = Buffer.from(base64Part, 'base64').toString('utf8');
    const [id, role, expiry] = decodedStr.split(':');
    
    if (Date.now() > parseInt(expiry, 10)) {
       return res.status(401).json({ success: false, message: 'Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại' });
    }

    const currentUser = await User.findById(id);
    
    if (!currentUser) {
      return res.status(401).json({ success: false, message: 'Người dùng không còn tồn tại' });
    }
    
    if (!currentUser.isActive) {
      return res.status(401).json({ success: false, message: 'Tài khoản đã bị khóa' });
    }
    
    req.user = currentUser;
    next();
  } catch (error) {
    return res.status(401).json({ success: false, message: 'Token không hợp lệ' });
  }
};

const authorize = (...roles) => {
  return (req, res, next) => {
    if (!roles.includes(req.user.role)) {
      return res.status(403).json({ success: false, message: 'Bạn không có quyền thực hiện hành động này' });
    }
    next();
  };
};

module.exports = { protect, authorize };
